#!/usr/bin/env python3
"""Generate `docs/API.md` — a per-function reference for the mmnet package.

Introspects every mmnet module (signatures + docstrings) so the reference never drifts from the
code. Re-run after changing the package:

    python tools/gen_api_docs.py
"""

from __future__ import annotations

import importlib
import inspect
import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

MODULES = [
    "mmnet.pipeline", "mmnet.config", "mmnet.io_readers", "mmnet.io_writers",
    "mmnet.steps.consolidate", "mmnet.steps.tag", "mmnet.steps.hubs",
    "mmnet.build", "mmnet.assemble", "mmnet.connect_extras", "mmnet.network",
    "mmnet.inspect", "mmnet.viz",
]

# The R oracle scripts are not Python-introspectable — describe them by hand.
R_ORACLE = [
    ("r_oracle/build_network.R", "The Stage-03 node-only oracle: build the per-mode sfnetwork "
     "(node + subdivide + smooth) and write the noded edges. R's only job; Python connects."),
    ("r_oracle/lib.R", "`clean_subnetwork` — the R noder (planar node + subdivide + smooth), "
     "copied verbatim from the Alaska R preprocess project; sourced by build_network.R."),
    ("r_oracle/CONTRACT.md", "The Python↔R node-only file-contract spec (WORKDIR layout, "
     "params/registry JSON)."),
]


def _first_para(obj) -> str:
    doc = inspect.getdoc(obj)
    if not doc:
        return "_(no docstring)_"
    return doc.strip().split("\n\n")[0].replace("\n", " ").strip()


def _lineno(obj) -> int:
    try:
        return inspect.getsourcelines(obj)[1]
    except (OSError, TypeError):
        return 0


def _sig(obj) -> str:
    try:
        return str(inspect.signature(obj))
    except (ValueError, TypeError):
        return "(...)"


def render_function(name: str, obj, level: str = "####") -> list[str]:
    return [f"{level} `{name}{_sig(obj)}`", "", _first_para(obj), ""]


def render_class(name: str, obj) -> list[str]:
    out = [f"### `class {name}`", "", _first_para(obj), ""]
    fields = getattr(obj, "model_fields", None)  # pydantic models
    if fields:
        out.append("**Fields:** " + ", ".join(f"`{f}`" for f in fields) + "\n")
    methods = [(n, m) for n, m in vars(obj).items()
               if inspect.isfunction(m) and not n.startswith("__")]
    methods.sort(key=lambda nm: _lineno(nm[1]))
    for n, m in methods:
        out.append(f"- `{n}{_sig(m)}` — {_first_para(m)}")
    out.append("")
    return out


def main() -> None:
    lines = [
        "# mmnet — API reference", "",
        "_Auto-generated by `tools/gen_api_docs.py` — do not edit by hand; re-run to refresh._",
        "", "See `docs/ARCHITECTURE.md` for the big picture and data flow.", "",
        "## Modules", "",
    ]
    lines += ["- [`" + m + "`](#" + m.replace(".", "").replace("_", "") + ")" for m in MODULES]
    lines.append("")

    for modname in MODULES:
        mod = importlib.import_module(modname)
        lines += [f"## `{modname}`", "", _first_para(mod), ""]
        members = [(n, o) for n, o in vars(mod).items()
                   if getattr(o, "__module__", None) == modname
                   and (inspect.isfunction(o) or inspect.isclass(o))]
        members.sort(key=lambda no: _lineno(no[1]))
        pub = [(n, o) for n, o in members if not n.startswith("_")]
        priv = [(n, o) for n, o in members if n.startswith("_")]

        for n, o in pub:
            lines += render_class(n, o) if inspect.isclass(o) else render_function(n, o)
        if priv:
            lines += ["<details><summary>private helpers</summary>", ""]
            for n, o in priv:
                lines.append(f"- `{n}{_sig(o)}` — {_first_para(o)}")
            lines += ["", "</details>", ""]

    lines += ["## R oracle scripts (`mmnet/r_oracle/`)", "",
              "Not Python-introspectable; described by hand.", "",
              "| script | role |", "| --- | --- |"]
    lines += [f"| `{p}` | {d} |" for p, d in R_ORACLE]
    lines.append("")

    out = ROOT / "docs" / "API.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    n_funcs = sum(1 for m in MODULES for _, o in vars(importlib.import_module(m)).items()
                  if getattr(o, "__module__", None) == m and inspect.isfunction(o))
    print(f"wrote {out.relative_to(ROOT)}  ({len(MODULES)} modules, ~{n_funcs} functions)")


if __name__ == "__main__":
    main()
